services:
  postgres:
    image: postgres:16-alpine
    container_name: nomna_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: NomNa
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - NomNa_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d NomNa"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nomna_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - NomNa_redis:/data

volumes:
  NomNa_db:
  NomNa_redis:
