services:
  postgres:
    image: postgres:16-alpine
    container_name: pulsechat_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pulsechat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - pulsechat_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pulsechat_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - pulsechat_redisdata:/data

volumes:
  pulsechat_pgdata:
  pulsechat_redisdata:
